name: daily-cron
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron API route
        run: |
          curl --request POST \
          --url 'https://likelist.xyz/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
